### ISSUE TITLE
subtitle to speech

### ISSUE THREAD

**Issue by ely2** [chychen/srt_to_tts#1]
It will be amazing if it can integrate a gui text to speech option that can from a subtitle file and the original track generate automatically a new track where each sequence is synchronized with the original (realistic voice choice, pitch rate) and the subtitle timing(synchronize speed rate with each sequence timing).

The original voice can be removed from each sequence using an opensource AI like "spleeter", or simply replace each sequence with the new one.

**Comment by chychen** [comment]
thanks for comments. however I don't have any plan to update it, please feel free to submit a PR or just copy to your own work.
